[package]
authors.workspace      = true
description            = "Miden faucet's logic"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["faucet", "miden"]
license.workspace      = true
name                   = "miden-faucet-lib"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
# Miden dependencies.
miden-client = { workspace = true }

# External dependencies.
serde     = { workspace = true }
thiserror = { workspace = true }
